Add type definition for pipeP and tryCatch
nowait/flow-typed pull request #1
Opened 2017-07-26 22:41 UTC by raychan

@briancavalier I added our local change for ramda to flow-type
I am wondering if there is better way to test?

2017-07-26 23:45 UTC, briancavalier requested changes
Thanks!  Looks good--just a few questions.  Hopefully, once we merge this to master, we can PR it from our fork to flowtype/flow-typed.

2017-07-26 23:45 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare type UnaryPromiseFn<A,R> = (a: A) => Promise<R>;
We could reuse `UnaryFn` here:

```js
declare type UnaryPromiseFn<A,R> = UnaryFn<A, Promise<R>>
```

It seems like we could do that to match the style of `UnarySameTypeFn` and `BinarySameTypeFn` below, which reuse `UnaryFn` and `BinaryFn`.

2017-07-26 23:45 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare var pipeP: PipeP;
I don't fully understand why they've chosen to use one style of declarations (intersection type plus `declare var`) for certain curried functions, like `pipe` and `pipeP`, and a different style of declarations (`declare function` variants) for other curried functions, like `tryCatch`.  Do you know?

It seems like the right thing to match the existing style, though, like you did :+1:

2017-07-26 23:45 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare function tryCatch<A, B, E>(tryer: (a: A, ...rest: Array<any>) => B): (((catcher: (e: E, a: A, ...rest: Array<any>) => B, a: A) => B) & ((catcher: (e: E, a: A, ...rest: Array<any>) => B) =>
Why use an intersection type to define the 3rd and 4th curried variants here instead of just adding a 4th `declare function`?

2017-07-26 23:45 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_functions.js
> +const tc4: string = tryCatch(tryFn, catchFn)(true);
This case, tc4, *seems* like it's the same as tc2 + tc3.  Is there a reason to have both?

2017-07-26 23:45 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_functions.js
> +const b: number = add2p(2)
Nice catch :+1:

2017-07-27 01:10 UTC, raychan commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare var pipeP: PipeP;
I don't, I am wondering too. Maybe different people contribute to this?

2017-07-27 01:16 UTC, raychan commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare function tryCatch<A, B, E>(tryer: (a: A, ...rest: Array<any>) => B): (((catcher: (e: E, a: A, ...rest: Array<any>) => B, a: A) => B) & ((catcher: (e: E, a: A, ...rest: Array<any>) => B) =>
I spend so much time to figure this out. I originally had 4 `declare function`, but test `tc5` or `tc6` will break. Only the 3rd declaration will be used.

2017-07-27 01:17 UTC, raychan commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/test_ramda_v0.x.x_functions.js
> +const tc4: string = tryCatch(tryFn, catchFn)(true);
true, I will delete it

2017-07-27 01:20 UTC, raychan commented
> Hopefully, once we merge this to master, we can PR it from our fork to flowtype/flow-typed.

Yes, I am pretty sure we can.

2017-07-27 14:38 UTC, raychan commented
I am wondering if we need to update for older flow versions?

2017-08-01 22:13 UTC, raychan commented
@briancavalier  Any more comments for this PR?

2017-08-02 01:16 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare var pipeP: PipeP;
Yeah, that's possible.  Seems like the maintainers would want to maintain a consistent style though.  Oh well, as long as we match the existing style, we should be ok.

2017-08-02 01:17 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare function tryCatch<A, B, E>(tryer: (a: A, ...rest: Array<any>) => B): (((catcher: (e: E, a: A, ...rest: Array<any>) => B, a: A) => B) & ((catcher: (e: E, a: A, ...rest: Array<any>) => B) =>
That's really strange.  I'll play around with it a bit.

2017-08-02 01:17 UTC, briancavalier commented
> I am wondering if we need to update for older flow versions?

We probably don't, but when we submit a PR to flow-typed, they may care.  So, we could do it now, or wait until we submit a PR.

2017-08-02 01:19 UTC, briancavalier commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare function tryCatch<A, B, E>(tryer: (a: A, ...rest: Array<any>) => B): (((catcher: (e: E, a: A, ...rest: Array<any>) => B, a: A) => B) & ((catcher: (e: E, a: A, ...rest: Array<any>) => B) =>
Hmmm, I wonder if the order of the declarations matters for some reason ...

2017-08-02 13:13 UTC, raychan commented on definitions/npm/ramda_v0.x.x/flow_v0.39.x-/ramda_v0.x.x.js
> +  declare function tryCatch<A, B, E>(tryer: (a: A, ...rest: Array<any>) => B): (((catcher: (e: E, a: A, ...rest: Array<any>) => B, a: A) => B) & ((catcher: (e: E, a: A, ...rest: Array<any>) => B) =>
😕

2017-08-02 13:24 UTC, raychan commented
ok, let's wait then

2017-08-02 18:26 UTC, briancavalier approved these changes
Nice work!

2017-08-02 18:32 UTC, merged