Update express
nowait/flow-typed pull request #2
Opened 2017-07-28 20:06 UTC by raychan

2017-07-28 20:14 UTC, raychan commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
> -  end: (data: string | Buffer, encoding: string) => this;
@briancavalier From express's document, end comes from Node core, specifically the [response.end() method of http.ServerResponse.](https://nodejs.org/api/http.html#http_response_end_data_encoding_callback) And the type definition is [here](https://github.com/facebook/flow/blob/master/lib/node.js#L1290) and it is different from our definition. But I can't figure out how to make [this part ](https://github.com/nowait/yelp-gil-service/blob/master/src/requestHandler/logging.js#L43-L57) type check. Any thoughts?

2017-07-31 19:29 UTC, raychan commented
Ok, @briancavalier I think this is ready for review.
I also created a [PR](https://github.com/nowait/yelp-gil-service/pull/241) on yelp_gil for this

2017-07-31 19:30 UTC, raychan commented
I will see if I can add some tests

2017-07-31 19:54 UTC, briancavalier requested changes
Looks good.  Only one minor suggestion

2017-07-31 19:54 UTC, briancavalier commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
> +  accepts(types: Array<string>): string | false;
:+1: One suggestion: move it up to line 41, so it's near the other `accepts` variant.

2017-07-31 19:54 UTC, briancavalier commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/express_v4.x.x.js
> +  req: express$Request;
It'll be interesting to see if we get feedback on this one when we PR it back to flow-types.  Express definitely uses it internally, but I wonder if it's something they don't want to expose publicly.  Let's keep it and see what happens 😄

2017-07-31 20:45 UTC, raychan commented
@briancavalier addressed your feedback and add few tests

2017-07-31 21:16 UTC, briancavalier requested changes
I think there's a leftover console.log.  Other than that, lgtm

2017-07-31 21:16 UTC, briancavalier commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
> +  console.log('request: ', res.req);
Leftover console.log?

2017-07-31 21:16 UTC, briancavalier commented on definitions/npm/express_v4.x.x/test_express_v4.x.x.js
> +    req.accepts(['json', 'text']);
:+1:

2017-07-31 21:30 UTC, raychan commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
> +  console.log('request: ', res.req);
Haha, this is actually a test. 😛  It just pop up in my head first. Any other suggestion?

2017-08-01 12:10 UTC, raychan commented
I opened a issue on flow's repo to improve http method's type definition.
https://github.com/facebook/flow/issues/4500

2017-08-01 22:10 UTC, raychan commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
> +  console.log('request: ', res.req);
I updated this test to match other [similar tests](https://github.com/nowait/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.32.x-/test_overrideUseMethodClassExtension.js#L55)

2017-08-02 01:13 UTC, briancavalier commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
> +  res.req;
Wow.  This works?  neat.  I was going to suggest:

```js
const r: $Request = res.req
```

But yours is even simpler 😄

2017-08-02 01:14 UTC, briancavalier commented
Looks good.  One question [here](https://github.com/nowait/flow-typed/pull/2/files/fca9c5d40145bd51c97dcf51f82923f497f9f8b9..34287e847cd37c0b41f8dbfd682dac4ca9401f61#r130766585) about the `res.req` test.  Otherwise, LGTM

2017-08-02 12:31 UTC, raychan commented on definitions/npm/express_v4.x.x/flow_v0.32.x-/test_response.js
> +  res.req;
yes, here are some similar tests: https://github.com/nowait/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.32.x-/test_overrideUseMethodClassExtension.js#L54-L59

2017-08-02 12:34 UTC, merged